#!/bin/bash
#SBATCH --job-name="SIM"
#SBATCH --output="/expanse/lustre/projects/iit119/dcooper/MOR/logs/SIM.%j.%N.out"
#SBATCH --partition=gpu-shared
#SBATCH --gpus=1
#SBATCH --nodes=1
#SBATCH --ntasks=5
#SBATCH --mem=32G
#SBATCH --account=iit119
#SBATCH -t 48:00:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=dcooper6@hawk.iit.edu

source ~/.bashrc

conda activate prep

cd $SLURM_SUBMIT_DIR

echo SIM BATCH JOB FOR $2
python SIMULATE.py $1 $2 $3 $4 $5 
